name: Check Server Time

on: 
  push:          # Trigger saat push ke repo
  # atau bisa pakai:
  # workflow_dispatch:  # Trigger manual dari UI GitHub

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Show current date and time
        run: date
