name: Scheduled Screener

on:
  schedule:
    - cron: '0 2 * * *'  # jalan tiap jam 2 pagi UTC (sesuaikan waktu)
  workflow_dispatch:     # buat bisa manual trigger

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Screener Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python sinyal_beli_screener.py
