name: Scheduled Screener

on:
  schedule:
    - cron: '5 2 * 1-5'  # jalan tiap jam 9:05 (sesuaikan waktu)
  workflow_dispatch:     # buat bisa manual trigger

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Show current date and time
        run: TZ=Asia/Jakarta date
        
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install openpyxl

      - name: Run sell_screener Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python sell_screener.py

      - name: Run buy_screener Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python buy_screener.py
